-- 1. Tabla de menus: el catalogo semanal que se publica
-- El PAE rota el menu por SEMANA del mes (1-4) y cada dia tiene una
-- comida DIFERENTE por jornada: una para Almuerzo y otra para Refrigerio.
-- Por eso cada fila es: semana + dia + jornada + platillo.
create table if not exists menus (
  id bigint generated by default as identity primary key,
  semana integer not null default 1,
  dia text not null,
  jornada text not null default 'Almuerzo',
  platillo text not null,
  descripcion text,
  calorias integer,
  imagen text,
  created_at timestamptz default now()
);

-- Migracion para bases que ya existian con el modelo anterior
-- (la columna "jornadas" era una lista). Se crean las columnas nuevas
-- si faltan, cada fila se queda con su primera jornada y se agrega
-- semana = 1. La columna vieja se elimina.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'menus' and column_name = 'jornadas'
  ) then
    alter table menus add column if not exists semana integer not null default 1;
    alter table menus add column if not exists jornada text not null default 'Almuerzo';
    update menus
    set jornada = case when array_length(jornadas, 1) >= 1 then jornadas[1] else 'Almuerzo' end
    where jornada is null or jornada = 'Almuerzo';
    execute 'alter table menus drop column jornadas';
  end if;
end $$;

-- 2. Tabla de reservas: los estudiantes que confirman comida
create table if not exists reservas (
  id bigint generated by default as identity primary key,
  estudiante text not null,
  documento text not null,
  sede text not null,
  turno text not null,
  fecha date not null,
  asistio boolean default false,
  grado text,
  created_at timestamptz default now()
);

-- Si la tabla ya existia sin la columna de asistencia, se agrega aca
alter table reservas add column if not exists asistio boolean default false;

-- El grado se guarda en cada reserva para saber el horario de su turno
alter table reservas add column if not exists grado text;

-- 2.1 Para llevar: la reserva puede indicar que la minuta se empaca
-- para llevarla a casa (Grab & Go). Ademas cada reserva tiene un
-- codigo corto unico (ej: 4K7QX2) que se imprime en la hoja de
-- entrega para que la cocina empare por nombre sin confundirse.
alter table reservas add column if not exists para_llevar boolean default false;
alter table reservas add column if not exists codigo text;
create index if not exists idx_reservas_codigo on reservas (codigo);

-- 3. Tabla de contactos: mensajes del formulario de contacto
create table if not exists contactos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null,
  mensaje text not null,
  created_at timestamptz default now()
);

-- Contactos: el admin puede marcarlos como leidos y responderles.
-- "documento" vincula el mensaje a un estudiante registrado (su
-- usuario en la tabla usuarios), asi ese estudiante ve la respuesta
-- al entrar con su sesion. "imagen" guarda la URL de una foto que
-- el remitente adjunto y "respuesta" la contestacion del admin.
alter table contactos add column if not exists leido boolean default false;
alter table contactos add column if not exists documento text;
alter table contactos add column if not exists imagen text;
alter table contactos add column if not exists respuesta text;
alter table contactos add column if not exists respuesta_at timestamptz;

-- 4. Tabla de avisos: noticias que publica el administrador
-- Se muestran en la pagina de inicio y el bot las conoce.
create table if not exists avisos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  texto text not null,
  fecha text,
  created_at timestamptz default now()
);

-- Los avisos tambien pueden llevar una imagen de referencia
alter table avisos add column if not exists imagen text;

-- 5. Tabla de beneficiarios: registro de los estudiantes del programa
-- La reserva valida que el documento exista aqui antes de guardarse.
create table if not exists beneficiarios (
  id bigint generated by default as identity primary key,
  documento text not null unique,
  nombre text not null,
  sede text not null,
  turno text not null,
  grado text,
  created_at timestamptz default now()
);

-- 5.1 Perfil de alimento del estudiante: "alergias" avisa a la cocina
-- (que lo ve resaltado en el panel) y "preferencias" permite pedir un
-- menu alternativo (Celiaco, Vegetariano o Vegano) si la sede lo ofrece.
alter table beneficiarios add column if not exists alergias text;
alter table beneficiarios add column if not exists preferencias text;

-- 6. Tabla de valoraciones: estrellas que dan los estudiantes a los platos
create table if not exists valoraciones (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references menus(id) on delete cascade,
  puntos integer not null check (puntos between 1 and 5),
  documento text,
  created_at timestamptz default now()
);

-- 6.1 Platos favoritos: cada estudiante marca sus platos preferidos.
-- La web le avisa "Hoy toca tu favorito" cuando uno aparece en el
-- menu del dia y la cocina ve la nota al preparar. Un documento puede
-- tener el mismo plato favorito solo una vez (la base lo rechaza por
-- duplicado, igual que hace con las reservas).
create table if not exists favoritos (
  id bigint generated by default as identity primary key,
  documento text not null,
  menu_id bigint not null references menus(id) on delete cascade,
  created_at timestamptz default now(),
  unique (documento, menu_id)
);
create index if not exists idx_favoritos_documento on favoritos (documento);

-- 7. Tabla de notificaciones: confirmaciones de reserva enviadas
create table if not exists notificaciones (
  id bigint generated by default as identity primary key,
  tipo text not null,
  destinatario text,
  mensaje text,
  enviado boolean default false,
  created_at timestamptz default now()
);

-- 8. Tabla de galeria: fotos propias del programa (eventos, equipo,
-- novedades) que publica el administrador. Se muestran en la Home.
create table if not exists galeria (
  id bigint generated by default as identity primary key,
  titulo text not null,
  imagen text not null,
  descripcion text,
  created_at timestamptz default now()
);

-- Si la tabla ya existia sin la descripcion, se la agregamos
alter table galeria add column if not exists descripcion text;

-- 9. Tabla de instituciones: las instituciones educativas cubiertas
-- por el PAE. Su cantidad alimenta la metrica real de la Home.
create table if not exists instituciones (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- 9.1 Tabla de sedes: los puntos donde se atiende a los estudiantes.
-- El admin puede agregar, renombrar y quitar sedes desde el panel, y
-- la reserva y el registro de beneficiarios las usan dinamicamente.
create table if not exists sedes (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- 9.2 Tabla de sobrantes: lo que el personal de cocina reporta que
-- quedo sin servir cada dia, por sede y jornada. Se registran porciones
-- y peso en kilogramos. Hay una sola fila por fecha + sede + jornada:
-- si se vuelve a guardar, se sobrescribe.
create table if not exists sobrantes (
  id bigint generated by default as identity primary key,
  fecha date not null,
  sede text not null,
  turno text not null,
  porciones integer,
  peso_kg numeric,
  creado_por text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (fecha, sede, turno)
);

-- 10. Tabla de usuarios: cuentas con login para el panel.
-- Cada rol ve solo las secciones que le corresponden:
--   admin        -> todo el panel
--   cocina       -> panel de cocina y menu
--   profesor     -> beneficiarios, asistencia y avisos
--   coordinador  -> avisos, galeria, instituciones, mensajes
--   estudiante   -> reserva propia, mis reservas y valorar platos
-- La clave se guarda SIEMPRE hasheada (sal:hash). El usuario es unico
-- (para estudiantes coincide con su numero de documento).
create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  usuario text not null unique,
  clave_hash text not null,
  rol text not null default 'estudiante',
  activo boolean default true,
  created_at timestamptz default now()
);

-- Las claves/PINs viven SOLO en clave_hash (el login verifica contra
-- el hash). La antigua columna "clave" en texto plano se elimino:
-- guardarla anulaba el hasheo y exponia todas las claves en un volcado
-- de la base. Para cambiar una clave se usa la edicion del panel.
alter table usuarios drop column if exists clave;

-- 10.2 Grupo asignado a cada profesor: sede + turno + grado. Con estos
-- datos la pestana Asistencia le muestra SOLO los reservados de su grupo
-- (los estudiantes de esa sede, turno y grado) para marcar quien asistio.
alter table usuarios add column if not exists sede text;
alter table usuarios add column if not exists turno text;
alter table usuarios add column if not exists grado text;

-- 10.3 Tabla de incidentes: reportes que hace el profesor sobre un
-- estudiante de su grupo (un incidente o una alergia). Cada reporte
-- llega al coordinador (y al admin), que puede marcarlo como resuelto.
-- "documento" identifica al estudiante y "reportado_por" guarda el
-- usuario del profesor que lo reporto, para que cada profesor vea
-- solo los que el mismo registro.
create table if not exists incidentes (
  id bigint generated by default as identity primary key,
  tipo text not null,
  estudiante text not null,
  documento text,
  sede text not null,
  grado text,
  descripcion text not null,
  fecha date not null,
  reportado_por text not null,
  resuelto boolean default false,
  resuelto_por text,
  resuelto_at timestamptz,
  created_at timestamptz default now()
);

-- Los reportes pueden llevar una foto adjunta (la URL la guarda el
-- backend en Supabase Storage al subirla desde el panel).
alter table incidentes add column if not exists imagen text;

-- 10.4 Avisos y menú: flujo borrador -> publicado. El coordinador (o el
-- admin) aprueba lo que redactó otro rol; la web solo muestra publicado.
alter table avisos add column if not exists estado text default 'publicado';
alter table menus add column if not exists estado text default 'publicado';

-- 10.41 La variante agrupa el platillo por tipo de dieta: Estandar,
-- Celiaco (sin gluten), Vegetariano y Vegano. La usa la pestana Menu
-- para filtrar el catalogo y los beneficiarios con preferencia la ven
-- primero en su reserva.
alter table menus add column if not exists variante text default 'Estandar';

-- 10.5 Tabla de settings: configuracion del sistema que se cambia desde
-- el panel sin tocar el codigo. Guarda pares clave-valor:
--   hora_limite_reserva: "08:00" (a esa hora se cierran las reservas y
--     cancelaciones para el MISMO dia).
--   cupos_sede: JSON con el cupo maximo de reservas por sede y fecha,
--     ej: {"Sede A": 50, "Sede B": 40}.
create table if not exists settings (
  clave text primary key,
  valor text,
  updated_at timestamptz default now()
);

-- Valores por defecto: limite de reserva a las 8am y sin cupos. El
-- admin los cambia desde el panel (pestana Configuracion).
insert into settings (clave, valor) values
  ('hora_limite_reserva', '08:00'),
  ('cupos_sede', '{}')
on conflict (clave) do nothing;

-- 10.6 Tabla de turnos de cocina: que persona del personal de cocina
-- atiende cada dia y en que sede. La asigna el coordinador o el admin.
create table if not exists turnos_cocina (
  id bigint generated by default as identity primary key,
  fecha date not null,
  usuario text not null,
  sede text,
  creado_por text,
  created_at timestamptz default now(),
  unique (fecha, usuario)
);

-- 10.7 Tabla de auditoria: registro de las acciones importantes que se
-- hacen en el panel (quien hizo que y cuando). Solo lectura para admin.
create table if not exists auditoria (
  id bigint generated by default as identity primary key,
  usuario text,
  rol text,
  accion text not null,
  detalle text,
  created_at timestamptz default now()
);

-- 10.8 Historial del chatbot del PAE: guarda cada mensaje del
-- estudiante y su respuesta para que la conversacion no se pierda
-- al recargar o cambiar de pagina. Sesion anonima por navegador.
create table if not exists chatbot_mensajes (
  id bigint generated always as identity primary key,
  sesion_id text not null,
  rol text not null check (rol in ('usuario','bot')),
  texto text not null,
  created_at timestamptz not null default now()
);
create index if not exists chatbot_mensajes_sesion_idx on chatbot_mensajes (sesion_id, id);

-- 10.9 Arcade PAE (Videojuegos educativos comunitarios)
create table if not exists juegos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text,
  instrucciones text,
  categoria text not null default 'Nutrición y Salud',
  tipo text not null default 'scratch', -- 'scratch', 'html_archivo', 'zip'
  url_recurso text not null,
  portada_url text,
  autor_documento text not null,
  autor_nombre text not null,
  autor_grado text,
  estado text not null default 'pendiente', -- 'pendiente', 'aprobado', 'rechazado'
  motivo_rechazo text,
  vistas integer not null default 0,
  dispositivo text not null default 'ambos', -- 'pc', 'movil', 'ambos'
  version text default '1.0',
  novedades text,
  actualizado_en timestamptz,
  actualizacion_pendiente jsonb,
  created_at timestamptz default now()
);

create index if not exists juegos_estado_idx on juegos (estado);
create index if not exists juegos_categoria_idx on juegos (categoria);
create index if not exists juegos_dispositivo_idx on juegos (dispositivo);

-- Tabla de historial de versiones del Arcade PAE (versionado de juegos)
create table if not exists juegos_versiones (
  id bigint generated by default as identity primary key,
  juego_id bigint not null references juegos(id) on delete cascade,
  version text not null default '1.0',
  novedades text,
  url_recurso text,
  portada_url text,
  dispositivo text default 'ambos', -- 'pc', 'movil', 'ambos'
  creada_en timestamptz default now()
);

create index if not exists juegos_versiones_juego_idx on juegos_versiones (juego_id, creada_en desc);

-- ============================================================
-- 4. Politicas de acceso (RLS)
-- ============================================================
-- IMPORTANTE: el frontend NUNCA habla directo con Supabase, todo
-- pasa por la API del backend. Por eso RLS se usa para proteger
-- los datos si alguien llega con el anon key:
--
--   * Publico (anon): SOLO lectura de lo que se muestra en la web
--     (menus, avisos, galeria, valoraciones). Nada de borrar.
--   * Privado: reservas, beneficiarios, contactos, notificaciones
--     NO se pueden leer con el anon key. El backend accede con la
--     SUPABASE_SERVICE_ROLE_KEY, que ignora RLS y ya valida por su
--     cuenta quien puede hacer cada operacion.
--
-- La escritura (crear/actualizar/borrar) queda en manos del backend.
-- Antes de cada create policy se borra la que ya exista, asi este
-- script se puede correr cuantas veces se quiera sin dar error.
-- ============================================================

-- menus: cualquiera puede ver el menu publicado
alter table menus enable row level security;
drop policy if exists "menus_lectura_publica" on menus;
create policy "menus_lectura_publica" on menus
  for select using (true);

-- reservas: datos personales, no se leen con el anon key
alter table reservas enable row level security;
drop policy if exists "reservas_lectura_publica" on reservas;
create policy "reservas_lectura_publica" on reservas
  for select using (false);

-- contactos: datos personales, no se leen con el anon key
alter table contactos enable row level security;
drop policy if exists "contactos_lectura_publica" on contactos;
create policy "contactos_lectura_publica" on contactos
  for select using (false);

-- avisos: cualquiera puede ver las noticias
alter table avisos enable row level security;
drop policy if exists "avisos_lectura_publica" on avisos;
create policy "avisos_lectura_publica" on avisos
  for select using (true);

-- beneficiarios: datos personales, no se leen con el anon key
alter table beneficiarios enable row level security;
drop policy if exists "beneficiarios_lectura_publica" on beneficiarios;
create policy "beneficiarios_lectura_publica" on beneficiarios
  for select using (false);

-- valoraciones: las estrellas se ven en la web
alter table valoraciones enable row level security;
drop policy if exists "valoraciones_lectura_publica" on valoraciones;
create policy "valoraciones_lectura_publica" on valoraciones
  for select using (true);

-- favoritos: datos personales del estudiante, no se leen con el anon key
alter table favoritos enable row level security;
drop policy if exists "favoritos_lectura_publica" on favoritos;
create policy "favoritos_lectura_publica" on favoritos
  for select using (false);

-- notificaciones: datos internos, no se leen con el anon key
alter table notificaciones enable row level security;
drop policy if exists "notificaciones_lectura_publica" on notificaciones;
create policy "notificaciones_lectura_publica" on notificaciones
  for select using (false);

-- galeria: cualquiera puede ver las fotos del programa
alter table galeria enable row level security;
drop policy if exists "galeria_lectura_publica" on galeria;
create policy "galeria_lectura_publica" on galeria
  for select using (true);

-- instituciones: datos de las metricas de la Home
alter table instituciones enable row level security;
drop policy if exists "instituciones_lectura_publica" on instituciones;
create policy "instituciones_lectura_publica" on instituciones
  for select using (true);

-- sedes: se ven en la web (reserva, registro por sede de la Home)
alter table sedes enable row level security;
drop policy if exists "sedes_lectura_publica" on sedes;
create policy "sedes_lectura_publica" on sedes
  for select using (true);

-- usuarios: credenciales, NO se leen con el anon key (el backend
-- valida el login con la service role key y las politicas son inaccesibles)
alter table usuarios enable row level security;
drop policy if exists "usuarios_lectura_publica" on usuarios;
create policy "usuarios_lectura_publica" on usuarios
  for select using (false);

-- sobrantes: datos internos, no se leen con el anon key
alter table sobrantes enable row level security;
drop policy if exists "sobrantes_lectura_publica" on sobrantes;
create policy "sobrantes_lectura_publica" on sobrantes
  for select using (false);

-- incidentes: datos de estudiantes, no se leen con el anon key
alter table incidentes enable row level security;
drop policy if exists "incidentes_lectura_publica" on incidentes;
create policy "incidentes_lectura_publica" on incidentes
  for select using (false);

-- settings: configuracion interna, no se lee con el anon key
alter table settings enable row level security;
drop policy if exists "settings_lectura_publica" on settings;
create policy "settings_lectura_publica" on settings
  for select using (false);

-- turnos_cocina: datos internos, no se leen con el anon key
alter table turnos_cocina enable row level security;
drop policy if exists "turnos_cocina_lectura_publica" on turnos_cocina;
create policy "turnos_cocina_lectura_publica" on turnos_cocina
  for select using (false);

-- auditoria: registro interno, no se lee con el anon key
alter table auditoria enable row level security;
drop policy if exists "auditoria_lectura_publica" on auditoria;
create policy "auditoria_lectura_publica" on auditoria
  for select using (false);

-- ============================================================
-- 4.1 Bucket de imagenes (Supabase Storage)
-- ============================================================
-- La carpeta es publica para que el navegador pueda mostrar las
-- fotos (la URL se comparte tal cual). Subir y borrar solo lo hace
-- el backend con la service role key; el anon key no puede.
-- ============================================================
insert into storage.buckets (id, name, public)
values ('imagenes', 'imagenes', true)
on conflict (id) do nothing;

drop policy if exists "imagenes_leer" on storage.objects;
create policy "imagenes_leer" on storage.objects
  for select using (bucket_id = 'imagenes');

-- ============================================================
-- 5. Datos de ejemplo: menu del PAE
-- El menu rota por semana del mes (1-4) y cada dia tiene una comida
-- DIFERENTE por jornada (Almuerzo y Refrigerio). Se inserta la
-- semana 1 y 2 completa como ejemplo; las semanas 3 y 4 las puede
-- cargar el administrador desde el panel.
-- Solo se insertan si la tabla esta vacia (evita duplicados)
-- ============================================================
insert into menus (semana, dia, jornada, platillo, descripcion, calorias, imagen)
select datos.semana, datos.dia, datos.jornada, datos.platillo, datos.descripcion,
       datos.calorias, datos.imagen
from (values
  -- Semana 1
  (1, 'Lunes', 'Almuerzo', 'Arroz con pollo y ensalada', 'Arroz, pollo guisado, ensalada fresca y jugo natural.', 520, NULL),
  (1, 'Lunes', 'Refrigerio', 'Sandwich de queso y fruta', 'Sandwich integral con queso, manzana y agua.', 340, NULL),
  (1, 'Martes', 'Almuerzo', 'Sopa de verduras y pan', 'Sopa de verduras de temporada con pan integral.', 380, NULL),
  (1, 'Martes', 'Refrigerio', 'Yogurt con avena', 'Yogurt con avena y trozos de platano.', 320, NULL),
  (1, 'Miercoles', 'Almuerzo', 'Pasta con salsa de tomate', 'Pasta integral con salsa casera de tomate y queso.', 460, NULL),
  (1, 'Miercoles', 'Refrigerio', 'Empanada de carne y jugo', 'Empanada horneada de carne con jugo de naranja.', 380, NULL),
  (1, 'Jueves', 'Almuerzo', 'Pescado con arroz y platano', 'Pescado al horno, arroz blanco y platano asado.', 490, NULL),
  (1, 'Jueves', 'Refrigerio', 'Arepa con queso y chocolate', 'Arepa de maiz con queso y chocolate caliente.', 400, NULL),
  (1, 'Viernes', 'Almuerzo', 'Sancocho de gallina', 'Sancocho tradicional con yuca, platano y papa.', 550, NULL),
  (1, 'Viernes', 'Refrigerio', 'Galletas de avena y leche', 'Galletas de avena con un vaso de leche.', 300, NULL),
  -- Semana 2
  (2, 'Lunes', 'Almuerzo', 'Carne guisada con arroz', 'Carne guisada, arroz blanco, frijoles y ensalada.', 540, NULL),
  (2, 'Lunes', 'Refrigerio', 'Pan con huevo y mango', 'Pan con huevo y rodajas de mango.', 350, NULL),
  (2, 'Martes', 'Almuerzo', 'Arroz con pollo y frijol', 'Arroz con pollo, frijol caliente y platano.', 530, NULL),
  (2, 'Martes', 'Refrigerio', 'Avena con pan', 'Avena caliente con pan de yuca.', 330, NULL),
  (2, 'Miercoles', 'Almuerzo', 'Pechuga a la plancha con verdura', 'Pechuga a la plancha con verduras salteadas y arroz.', 470, NULL),
  (2, 'Miercoles', 'Refrigerio', 'Fruta con galleta', 'Porcion de fruta variada con galleta integral.', 260, NULL),
  (2, 'Jueves', 'Almuerzo', 'Cazuela de frijoles', 'Cazuela de frijoles con arroz y aguacate.', 520, NULL),
  (2, 'Jueves', 'Refrigerio', 'Bocadillo con queso y agua', 'Bocadillo de guayaba con queso y agua.', 310, NULL),
  (2, 'Viernes', 'Almuerzo', 'Sudado de pollo con arroz', 'Sudado de pollo con papas, arroz y ensalada.', 500, NULL),
  (2, 'Viernes', 'Refrigerio', 'Sorbete de frutas y galleta', 'Sorbete de frutas naturales con galleta.', 290, NULL)
) as datos(semana, dia, jornada, platillo, descripcion, calorias, imagen)
where not exists (select 1 from menus);

-- Instituciones educativas de ejemplo (metricas reales de la Home)
insert into instituciones (nombre)
select datos.nombre
from (values
  ('I.E. San Jose'),
  ('I.E. La Esperanza'),
  ('I.E. Gabriel Garcia Marquez'),
  ('I.E. Nueva Granada'),
  ('I.E. El Rosario'),
  ('I.E. Ciudadela Educativa'),
  ('I.E. Rafael Nunez')
) as datos(nombre)
where not exists (select 1 from instituciones);

-- Sedes de ejemplo (puntos de atencion del PAE). El admin las puede
-- agregar, renombrar o quitar desde el panel. Solo se insertan si la
-- tabla esta vacia para no pisar las que ya haya creado el admin.
insert into sedes (nombre)
select datos.nombre
from (values
  ('Sede A'),
  ('Sede B'),
  ('Sede C')
) as datos(nombre)
where not exists (select 1 from sedes);

-- Avisos de ejemplo: solo si la tabla esta vacia
insert into avisos (titulo, texto, fecha)
select datos.titulo, datos.texto, datos.fecha
from (values
  ('Suspension del servicio', 'Viernes no habra servicio por jornada pedagogica. Las minutas se reprogramaran.', 'Permanece atento'),
  ('Reserva de minutas en linea', 'Ya puedes reservar tu comida desde la aplicacion para evitar el desperdicio.', 'Novedad'),
  ('Actualizacion de datos', 'Mantén actualizada la informacion de los estudiantes para el programa.', 'Recordatorio')
) as datos(titulo, texto, fecha)
where not exists (select 1 from avisos);

-- Beneficiarios de ejemplo: solo si la tabla esta vacia
-- Estos documentos son los que puede usar un estudiante para reservar
insert into beneficiarios (documento, nombre, sede, turno, grado)
select datos.documento, datos.nombre, datos.sede, datos.turno, datos.grado
from (values
  ('1234567890', 'Ana Maria Lopez', 'Sede A', 'Almuerzo', '5'),
  ('2345678901', 'Carlos Andres Perez', 'Sede A', 'Refrigerio', '3'),
  ('3456789012', 'Laura Valentina Gomez', 'Sede B', 'Almuerzo', '7'),
  ('4567890123', 'Sebastian Rodriguez', 'Sede B', 'Refrigerio', '9'),
  ('5678901234', 'Valentina Torres', 'Sede C', 'Almuerzo', '11'),
  ('6789012345', 'Andres Felipe Ramirez', 'Sede C', 'Refrigerio', '6'),
  ('7890123456', 'Sofia Martinez', 'Sede A', 'Almuerzo', '4'),
  ('8901234567', 'Juan Pablo Castro', 'Sede B', 'Refrigerio', '10'),
  ('9012345678', 'Mariana Suarez', 'Sede C', 'Almuerzo', '8'),
  ('0123456789', 'Daniel Vargas', 'Sede A', 'Refrigerio', '2')
) as datos(documento, nombre, sede, turno, grado)
where not exists (select 1 from beneficiarios);

-- Valoraciones de ejemplo: algunas estrellas ya puestas por los
-- estudiantes (solo si la tabla esta vacia)
insert into valoraciones (menu_id, puntos, documento)
select m.id, datos.puntos, datos.documento
from (values
  ('Arroz con pollo y ensalada', 5, '1234567890'),
  ('Arroz con pollo y ensalada', 4, '7890123456'),
  ('Sopa de verduras y pan', 3, '2345678901'),
  ('Pasta con salsa de tomate', 4, '5678901234'),
  ('Pescado con arroz y platano', 5, '3456789012'),
  ('Sancocho de gallina', 5, '9012345678'),
  ('Sancocho de gallina', 4, '4567890123')
) as datos(platillo, puntos, documento)
join menus m on m.platillo = datos.platillo and m.semana = 1 and m.jornada = 'Almuerzo'
where not exists (select 1 from valoraciones);

-- ============================================================
-- SEGURIDAD DE LA BASE (resumen; detalle en sql/seguridad.sql)
-- ============================================================
-- RLS activo en todas las tablas y SIN politicas para el rol
-- publico/anon: el frontend nunca habla con Supabase directo,
-- todo pasa por el backend con la service_role key (que ignora
-- RLS por diseno). Asi, aunque alguien consiga la anon key,
-- no puede leer ni escribir ni una fila.
alter table auditoria enable row level security;
alter table avisos enable row level security;
alter table beneficiarios enable row level security;
alter table chatbot_mensajes enable row level security;
alter table chat_mensajes enable row level security;
alter table colaboradores enable row level security;
alter table contactos enable row level security;
alter table favoritos enable row level security;
alter table galeria enable row level security;
alter table incidentes enable row level security;
alter table instituciones enable row level security;
alter table menus enable row level security;
alter table notificaciones enable row level security;
alter table reservas enable row level security;
alter table sedes enable row level security;
alter table settings enable row level security;
alter table sobrantes enable row level security;
alter table turnos_cocina enable row level security;
alter table usuarios enable row level security;
alter table valoraciones enable row level security;

-- Unica reserva por documento + fecha + turno (la base rechaza el
-- duplicado aunque dos peticiones lleguen al mismo tiempo)
delete from reservas a using reservas b
  where a.id > b.id and a.documento = b.documento
    and a.fecha = b.fecha and a.turno = b.turno;
alter table reservas drop constraint if exists reservas_unicas;
alter table reservas add constraint reservas_unicas unique (documento, fecha, turno);

-- Indices de las consultas frecuentes
create index if not exists idx_reservas_documento on reservas (documento);
create index if not exists idx_reservas_fecha on reservas (fecha);
create index if not exists idx_reservas_fecha_sede on reservas (fecha, sede);
create index if not exists idx_valoraciones_menu on valoraciones (menu_id);
create index if not exists idx_auditoria_creado on auditoria (created_at desc);
