import pg from "pg";
import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(import.meta.dirname, "../.env") });

const client = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: false,
});

async function run() {
  await client.connect();
  console.log("Conectado a PostgreSQL en Supabase...");
  const sql = `
    create table if not exists juegos (
      id bigint generated by default as identity primary key,
      titulo text not null,
      descripcion text,
      instrucciones text,
      categoria text not null default 'Nutrición y Salud',
      tipo text not null default 'scratch',
      url_recurso text not null,
      portada_url text,
      autor_documento text not null,
      autor_nombre text not null,
      autor_grado text,
      estado text not null default 'pendiente',
      motivo_rechazo text,
      vistas integer not null default 0,
      created_at timestamptz default now()
    );

    create index if not exists juegos_estado_idx on juegos (estado);
    create index if not exists juegos_categoria_idx on juegos (categoria);
  `;
  await client.query(sql);
  console.log("✅ Migración exitosa: tabla 'juegos' lista.");
  await client.end();
}

run().catch((err) => {
  console.error("❌ Error en migración:", err);
  process.exit(1);
});
